apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: soliman/client
      context: client
      docker:
        dockerfile: Dockerfile 
      sync: 
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: soliman/comments
      context: comments
      docker:
        dockerfile: Dockerfile 
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: soliman/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile 
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: soliman/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile 
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: soliman/posts
      context: posts
      docker:
        dockerfile: Dockerfile 
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: soliman/query
      context: query
      docker:
        dockerfile: Dockerfile 
      sync: 
        manual:
          - src: '*.js'
            dest: .